
################
# Springboot
################
spring:
#   mustache:
#      suffix: .html

   # JPA Configuration
   jpa:
      show-sql: true
      # JPA Properties
      properties:
         hibernate:
            #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            #dialect: org.hibernate.dialect.DerbyTenSevenDialect
            # Dialect erkennt Spring Boot !
            # Zumindest für HSQL

      # Hibernate Properties
      hibernate:
         # Hibernate DDL (create, create-drop, validate, update, none)
         ddl-auto: validate
         
   flyway:
      enabled: true
         
   
################
# Data source
################
datasource:
   local:
   
      # HSQL 
      # lokal
      #jdbcUrl: jdbc:hsqldb:projects-db/hsqldb   
      # Server
      jdbcUrl: jdbc:hsqldb:hsql://localhost/cakedb            
      # In-Memory DB
      #jdbcUrl: jdbc:hsqldb:mem:projects-db
      #user: property set with -D at startup
      #password: property set with -D at startup
            