create table catalog 
(id bigint generated by default as identity (start with 1), 
created timestamp, 
updated timestamp, 
version integer not null, 
name varchar(255), 
price double not null, 
shortcut varchar(10) not null, 
primary key (id));
alter table catalog add constraint UK_9e9lah6o6slko4ljnbgo15c87 unique (shortcut);
